const C={R:'Registrations',F:'Event Config',L:'Check-In Log',D:{EVENT_NAME:"Parkinson's Disease Warriors Philippines – Get Together 2027",THEME:'New Hope: Moving Forward Beyond Parkinson’s',EVENT_DATE:'January 16, 2027',EVENT_TIME:'9:00 AM–1:00 PM',VENUE:'St. Luke’s Medical Center – Quezon City',EVENT_NOTE:'A minimal fee may apply for food and beverages.',ORGANIZER_EMAIL:'',ADMIN_PIN:'2027',REGISTRATION_OPEN:'YES',MAX_REGISTRATIONS:'0'}};
const H=['Registration ID','Token','Date Submitted','Full Name','Mobile Number','Email Address','City / Province','Participant Type','Number of Companions','Accessibility / Assistance Request','Dietary Concern','Emergency Contact Name','Emergency Contact Number','Privacy Consent','Status','Checked In At','Checked In By'];
const LH=['Timestamp','Registration ID','Full Name','Action','Staff Name'];
function onOpen(){SpreadsheetApp.getUi().createMenu('PDW 2027').addItem('Setup / Repair','setupSystem').addToUi()}
function setupSystem(){const s=SpreadsheetApp.getActive();let r=s.getSheetByName(C.R)||s.insertSheet(C.R),f=s.getSheetByName(C.F)||s.insertSheet(C.F),l=s.getSheetByName(C.L)||s.insertSheet(C.L);hdr(r,H);hdr(l,LH);if(f.getLastRow()==0){f.getRange(1,1,11,2).setValues([['Setting','Value'],...Object.entries(C.D)])}style(r,H.length);style(f,2);style(l,LH.length);r.setFrozenRows(1);f.setFrozenRows(1);l.setFrozenRows(1);PropertiesService.getScriptProperties().setProperty('SID',s.getId());SpreadsheetApp.getUi().alert('Setup complete. Edit Event Config, then deploy as Web App.')}
function doGet(e){const p=e&&e.parameter&&e.parameter.page==='checkin'?'CheckIn':'Index',t=HtmlService.createTemplateFromFile(p);t.config=pub();return t.evaluate().setTitle(p==='CheckIn'?'PDW 2027 Check-In':'PDW 2027 Registration').addMetaTag('viewport','width=device-width, initial-scale=1').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)}
function registerGuest(f){if(!f)throw Error('No data received.');['fullName','mobile','email','cityProvince','participantType'].forEach(k=>{if(!String(f[k]||'').trim())throw Error('Please complete all required fields.')});if(!f.privacyConsent)throw Error('Please agree to the privacy notice.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(f.email))throw Error('Enter a valid email address.');const g=cfg();if(String(g.REGISTRATION_OPEN).toUpperCase()!=='YES')throw Error('Registration is closed.');const sh=ss().getSheetByName(C.R),lock=LockService.getScriptLock();lock.waitLock(15000);try{const dup=duplicate(sh,f);if(dup)return{ok:true,duplicate:true,registrationId:dup.id,qrPayload:`PDW2027|${dup.id}|${dup.tok}`};const max=+g.MAX_REGISTRATIONS||0,count=Math.max(0,sh.getLastRow()-1);if(max&&count>=max)throw Error('Registration is full.');const id=nextId(sh),tok=Utilities.getUuid().replace(/-/g,'').slice(0,20),qr=`PDW2027|${id}|${tok}`,row=[id,tok,new Date(),cl(f.fullName,120),cl(f.mobile,40),cl(f.email,160),cl(f.cityProvince,120),cl(f.participantType,100),+f.companions||0,cl(f.accessibility,500),cl(f.dietary,500),cl(f.emergencyName,120),cl(f.emergencyNumber,40),'YES','REGISTERED','',''];sh.appendRow(row);let attendeeEmailSent=false,organizerEmailSent=false;try{attendeeEmailSent=mailAtt(g,row,qr)}catch(e){console.error(e)}try{organizerEmailSent=mailOrg(g,row)}catch(e){console.error(e)}return{ok:true,registrationId:id,qrPayload:qr,attendeeEmailSent,organizerEmailSent}}finally{lock.releaseLock()}}
function loginAdmin(pin,staff){const g=cfg();if(String(pin||'').trim()!==String(g.ADMIN_PIN||'').trim())throw Error('Incorrect staff PIN.');staff=cl(staff,100);if(!staff)throw Error('Enter staff name.');const t=Utilities.getUuid();CacheService.getScriptCache().put('a:'+t,JSON.stringify({staff}),7200);return{ok:true,token:t,staffName:staff}}
function getDashboardStats(t){auth(t);const sh=ss().getSheetByName(C.R),n=sh.getLastRow();if(n<2)return{total:0,checkedIn:0,pending:0,companions:0};const a=sh.getRange(2,1,n-1,17).getValues();let c=0,p=0;a.forEach(r=>{if(String(r[14]).toUpperCase()==='ATTENDED')c++;p+=+r[8]||0});return{total:a.length,checkedIn:c,pending:a.length-c,companions:p}}
function searchGuest(t,q){auth(t);q=norm(q);const qm=mob(q),sh=ss().getSheetByName(C.R),n=sh.getLastRow();if(n<2||(!q&&!qm))return[];return sh.getRange(2,1,n-1,17).getValues().filter(r=>norm(r[0]).includes(q)||norm(r[3]).includes(q)||(qm&&mob(r[4]).includes(qm))).slice(0,25).map(r=>({registrationId:r[0],fullName:r[3],mobileLast4:mob(r[4]).slice(-4),participantType:r[7],companions:r[8],status:r[14],checkedInAt:r[15]?fd(r[15]):''}))}
function checkInByQr(t,q){const a=auth(t),p=String(q||'').split('|');if(p.length!==3||p[0]!=='PDW2027')throw Error('Invalid QR code.');return mark(p[1],p[2],a.staff,'QR')}
function manualCheckIn(t,id){return mark(id,null,auth(t).staff,'MANUAL')}
function mark(id,tok,staff,method){const s=ss(),sh=s.getSheetByName(C.R),lg=s.getSheetByName(C.L),n=sh.getLastRow();if(n<2)throw Error('No registrations found.');const a=sh.getRange(2,1,n-1,17).getValues(),lock=LockService.getScriptLock();lock.waitLock(12000);try{for(let i=0;i<a.length;i++){const r=a[i];if(String(r[0])===String(id)){if(tok&&String(r[1])!==String(tok))throw Error('QR validation failed.');if(String(r[14]).toUpperCase()==='ATTENDED')return{ok:true,alreadyCheckedIn:true,registrationId:r[0],fullName:r[3],participantType:r[7],companions:r[8],checkedInAt:r[15]?fd(r[15]):''};const now=new Date(),rn=i+2;sh.getRange(rn,15,1,3).setValues([['ATTENDED',now,staff]]);lg.appendRow([now,r[0],r[3],method+' CHECK-IN',staff]);return{ok:true,alreadyCheckedIn:false,registrationId:r[0],fullName:r[3],participantType:r[7],companions:r[8],checkedInAt:fd(now)}}}throw Error('Registration ID not found.')}finally{lock.releaseLock()}}
function duplicate(sh,f){const n=sh.getLastRow();if(n<2)return null;const a=sh.getRange(2,1,n-1,6).getValues(),name=norm(f.fullName),m=mob(f.mobile),e=norm(f.email);for(const r of a)if(norm(r[3])===name&&((m&&mob(r[4])===m)||(e&&norm(r[5])===e)))return{id:r[0],tok:r[1]};return null}
function nextId(sh){let x=0,n=sh.getLastRow();if(n>1)sh.getRange(2,1,n-1,1).getDisplayValues().flat().forEach(v=>{const m=String(v).match(/^PDW-2027-(\d+)$/);if(m)x=Math.max(x,+m[1])});return'PDW-2027-'+String(x+1).padStart(4,'0')}
function mailAtt(g,r,qr){if(!r[5])return false;const u='https://quickchart.io/qr?size=260&margin=2&text='+encodeURIComponent(qr),h=`<div style="font-family:Arial;max-width:620px"><h2>Registration Confirmed</h2><p>Hi <b>${esc(r[3])}</b>, your registration is confirmed.</p><p><b>ID:</b> ${r[0]}<br><b>Date:</b> ${esc(g.EVENT_DATE)}<br><b>Time:</b> ${esc(g.EVENT_TIME)}<br><b>Venue:</b> ${esc(g.VENUE)}</p><p><img src="${u}" width="230"></p><p>Show this QR code at check-in.</p></div>`;MailApp.sendEmail({to:r[5],subject:`You're Registered – ${g.EVENT_NAME}`,htmlBody:h,name:'PD Warriors Philippines'});return true}
function mailOrg(g,r){const to=String(g.ORGANIZER_EMAIL||'').trim();if(!to)return false;MailApp.sendEmail({to,subject:'New Get Together 2027 Registration – '+r[3],htmlBody:`<h2>New Registration</h2><p><b>${esc(r[3])}</b><br>${esc(r[5])}<br>${esc(r[4])}<br>${esc(r[7])}<br>ID: ${r[0]}</p>`,name:'PDW 2027 Registration'});return true}
function auth(t){const x=t&&CacheService.getScriptCache().get('a:'+t);if(!x)throw Error('Staff session expired. Please sign in again.');return JSON.parse(x)}
function pub(){const g=cfg();return{EVENT_NAME:g.EVENT_NAME,THEME:g.THEME,EVENT_DATE:g.EVENT_DATE,EVENT_TIME:g.EVENT_TIME,VENUE:g.VENUE,EVENT_NOTE:g.EVENT_NOTE,REGISTRATION_OPEN:g.REGISTRATION_OPEN}}
function cfg(){const s=ss(),f=s.getSheetByName(C.F),g=Object.assign({},C.D);if(f&&f.getLastRow()>1)f.getRange(2,1,f.getLastRow()-1,2).getDisplayValues().forEach(([k,v])=>{if(k)g[String(k).trim()]=String(v||'').trim()});return g}
function ss(){const id=PropertiesService.getScriptProperties().getProperty('SID');return id?SpreadsheetApp.openById(id):SpreadsheetApp.getActive()}
function hdr(sh,h){if(sh.getLastRow()==0||sh.getRange(1,1,1,h.length).getDisplayValues()[0].join('|')!==h.join('|'))sh.getRange(1,1,1,h.length).setValues([h])}
function style(sh,n){sh.getRange(1,1,1,n).setFontWeight('bold').setBackground('#0b5132').setFontColor('#fff')}
function cl(v,n){return String(v==null?'':v).trim().slice(0,n||500)}function norm(v){return cl(v,500).toLowerCase().replace(/\s+/g,' ')}function mob(v){return String(v==null?'':v).replace(/\D/g,'')}function fd(v){return Utilities.formatDate(new Date(v),Session.getScriptTimeZone()||'Asia/Manila','MMM d, yyyy h:mm a')}function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
